package com.kudu.mappin.model

data class Point(
    val id: String,
    val orden: String,
    val cod_prod: String,
    val prov: String,
    val dis: String,
    val crg: String,
    val punto_ref: String,
    val tipo: String,
    val empresa: String,
    val productor: String,
    val otro_prod: String,
    val clip: String,
    val ruc: String,
    val contacto: String,
    val tel_fijo: String,
    val cel: String,
    val area_sem: String,
    val area_cos: String,
    val fe_siem: String,
    val fe_cos: String,
    val produccion: String,
    val redim: String,
    val tpo: String,
    val coa: String,
    val cod_reg: String,
    val zona_reg: String,
    val ruta: String,
    val rubro: String,
    val estado: String,
    val coment: String,
    val observa: String,
    val responsabl: String,
    val fe_ac: String,
    val variedad: String,
)